.\" By David Busby <d.busby@saiweb.co.uk>
.\" Changelog
.\"
.\" - 28/09/10 - Created
.\"
.\"
.TH myisam_defrag.conf 7 "September 28, 2010"
.LO 7
.SH NAME
myisam_defrag.conf \- Configuration file for myisam_defrag
.SH AUTHOR
David Busby <d.busby@saiweb.co.uk>
.SH DESCRIPTION
.br
\- logfile=<logfile path> Specify the location to write logs to
.br
\- login_conf=<path> Specify the location of a mySQL file 
.br
\- frag_thresh=<int> Specify the pecentage fragmentation above or equal to which to run an optimize
